### ISSUE TITLE
Publish diode-react for ScalaJS 1.X

### ISSUE THREAD

**Issue by Fraer** [suzaku-io/diode#103]
Hello, there is a published version of diode for ScalaJS 1.X
https://search.maven.org/artifact/io.suzaku/diode_sjs1_2.13/1.1.9/jar

but it looks like there is no diode-react for ScalaJS 1.X
Could we expect diode-react_sjs1_2.13 anytime soon ?

**Comment by an-tex** [comment]
https://mvnrepository.com/artifact/io.suzaku/diode-react it's been published for 1.1.11
