### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by povder** [suzaku-io/diode#177]
Hello, are there any plans for implementing Scala 3 support?

**Comment by cquiroz** [comment]
I don't know if anybody is actively working on that. diode has a few macros that would make the task a bit harder.
PRs are welcome

**Comment by povder** [comment]
I'll give it a shot, work in progress in https://github.com/povder/diode/tree/scala3

**Comment by cquiroz** [comment]
Thanks @povder your fix has been merged

**Comment by Angel-O** [comment]
> Thanks @povder your fix has been merged

hey @cquiroz where can I find the artefacts compatible with scala 3 ?

**Comment by cquiroz** [comment]
I managed to make a release candidate at the end 1.2.0-RC1. It would be great to get some feedback before going 1.2.0 final

**Comment by Angel-O** [comment]
> I managed to make a release candidate at the end 1.2.0-RC1. It would be great to get some feedback before going 1.2.0 final

Sorry for the late reply, but I cannot see any artefact on [Maven](https://mvnrepository.com/artifact/io.suzaku/diode_2.13/1.2.0-RC3) with scala 3 support (the latest version `1.2.0-RC3` is complied against `scala 2.13`), am I missing something ? Are you suggesting to download the zip file from the releases tab and try it locally ?

**Comment by cquiroz** [comment]
You're right, something is wrong on the release task. I'll review it
