### ISSUE TITLE
ActionBatch fails to execute when handler defined

### ISSUE THREAD

**Issue by nadenf** [suzaku-io/diode#228]
The issue revolves around this code:
https://github.com/suzaku-io/diode/blob/master/diode-core/shared/src/main/scala/diode/Circuit.scala#L298

If a handler is defined than baseHandler is never called which means that ActionBatch actions are never executed.
It seems like the code should be reversed where you check if it's an ActionBatch first and then default to the provided handler.

And if you try and manually handle the ActionBatch yourself in your own handler it won't work because the ActionBatch class is not a case class:
https://github.com/suzaku-io/diode/blob/master/diode-core/shared/src/main/scala/diode/Circuit.scala#L46

**Comment by cquiroz** [comment]
Hi, thanks for reporting this. Would it help to change ActionBatch to be a case class?
If you have a fix PRs are welcome
