### ISSUE TITLE
Replace zoomRW with lenses

### ISSUE THREAD

**Issue by fdietze** [suzaku-io/diode#35]
There are many existing libraries:
* [Shapeless Lenses](https://github.com/milessabin/shapeless/wiki/Feature-overview:-shapeless-2.0.0#boilerplate-free-lenses-for-arbitrary-case-classes)
* [Monocle](https://julien-truffaut.github.io/Monocle/)
* ...

One could also create their own lenses specifically for diode using macros/meta without using additional dependencies. Something like [sauron](https://github.com/pathikrit/sauron).

**Comment by ochrons** [comment]
A simple lens implementation (with macros) is in the plans, and also integration for Monocle. Haven't gotten around to doing that yet, so contributions are welcome if anyone feels fluent with macro stuff 😜 

(or just copy the base implementation from Monocle 😄)

**Comment by fdietze** [comment]
@cornerman?

**Comment by fdietze** [comment]
What are the requirements?

Something that generates ZoomRW or ModelRW instances?

```scala
val counterHandler = new ActionHandler(@ZoomRW(_.company.address.street)) { ...
```

**Comment by fdietze** [comment]
For reference, here is the macro code from Monocle:
https://github.com/julien-truffaut/Monocle/blob/bd801df5a51dc02100652e899260842e12d7adb7/macro/shared/src/main/scala/monocle/macros/internal/Macro.scala#L13

**Comment by ochrons** [comment]
Support for a simple `zoom` lens added in 1.1.1
