### ISSUE TITLE
How to exclude `Pending` pots in PotMap action handler?

### ISSUE THREAD

**Issue by seigert** [suzaku-io/diode#41]
Hello,

I'm trying to work around multiple fetching of PotMap data during initial mount/render of React component. The code is very similar to examples here: https://diode.suzaku.io/advanced/PotCollection.html

I've tried to exclude (key, pot) pairs with `Pending` state from update keys set:
```scala
  def handle: PartialFunction[Any, ActionResult[M]] = {
    case update: UpdateUserOrders =>
      val current = value.seq
      val keys = update.keys.filterNot { k =>
        current.exists {
          case (id, pot) if id == k => pot.isPending
          case _ => false
        }
      }

      if (keys.nonEmpty) {
        val updateF = update.effect(AutowireClient[API].getUserOrders(keys).call())(_.mapValues(Ready(_)))
        update.handleWith(this, updateF)(AsyncAction.mapHandler(keys))
      } else noChange
  }
```

But as soon as I'm adding `noChange` as empty key set action result, model stops to update at all and stays in `Pending` state forever.

Could you point to me what I'm doing wrong? Or maybe there is a better way to stop unnecessary updates of common keys?

**Comment by ochrons** [comment]
This topic has been discussed on the Diode Gitter channel from time to time :)
