### ISSUE TITLE
 [A : ActionType] for EffectSingle ?

### ISSUE THREAD

**Issue by jhegedus42** [suzaku-io/diode#42]
https://github.com/suzaku-io/diode/blob/0e443dec08313ff4cc81fcbab71eb31a8dce6632/diode-core/shared/src/main/scala/diode/Effect.scala#L101

would it make sense to write something like:
```
class EffectSingle[A:ActionType] private[diode] (f: () => Future[A], ec: ExecutionContext) extends EffectBase(ec) {
  override def run(dispatch: Any => Unit) = f().map(dispatch)(ec)

  override def toFuture = f()
}
```

**Comment by ochrons** [comment]
Why?

**Comment by jhegedus42** [comment]
It seems that dispatch should only take `Actions` but I see that EffectSingle is private.. so it is not exposed, but would it be bad - for some reason - to express this constraint explicitly ? The more type safety the better, so why not? Might make reading the code easier since it's more explicit.

**Comment by ochrons** [comment]
The constraint is already in place in all the public facing methods under `Effect` object, so there is no need to replicate it in the private constructor. Internally actions are just `Any` in Diode and the type safety is only applied at the border, to make usage safe.

**Comment by jhegedus42** [comment]
I see, good to know the reasoning behind it, thanks for the explanation.
