### ISSUE TITLE
"inferred existential type" warning when putting ReactConnectorProxy in State

### ISSUE THREAD

**Issue by jcrosetto** [suzaku-io/diode#50]
I'm following the example in the Usage with React docs that suggest storing the ReactConnectorProxy in the State (in the example it has `case class State(component: ReactConnectProxy[Pot[String])`).

When doing that I am getting an "inferred existential type" warning. For example, doing

`case class State(component: ReactConnectorProxy[Model])`

results in

```
inferred existential type Option[japgolly.scalajs.react.ReactComponentC.ReqProps[diode.react.ModelProxy[Model] => japgolly.scalajs.react.ReactElement,Model,_$1,org.scalajs.dom.raw.Element]] forSome { type _$1 }, which cannot be expressed by wildcards,  should be enabled
by making the implicit value scala.language.existentials visible.
This can be achieved by adding the import clause 'import scala.language.existentials'
or by setting the compiler option -language:existentials.
See the Scaladoc for value scala.language.existentials for a discussion
why the feature should be explicitly enabled.
```

**Comment by ochrons** [comment]
Yea, I suppose the doc should mention the required import. It's just that this pattern of use is quite rare, as typically the `connect` is only used on the circuit level, like
```
val customerData = AppCircuit.connect(_.customerData)
```
where you don't need to specify the type explicitly.

**Comment by jcrosetto** [comment]
Just wanted to make sure it was expected. Thanks!
