### ISSUE TITLE
Support for scalajs-react 1.0.0

### ISSUE THREAD

**Issue by tarsa** [suzaku-io/diode#57]
Right now I'm basically forced to host a verbatim copy of diode-react from [a branch](https://github.com/suzaku-io/diode/tree/scalajs-react-1.0.0/diode-react/src/main/scala/diode/react) in a subdirectory in my project [here](https://github.com/tarsa/TarsaLZP/tree/52255d3353d9ac39058a08be3c1ff48cab5e906c/scalajs/TarsaLZP/src/main/scala/diode/react)

Having an official updated artifact (of diode-react) as a dependency would be a lot better.

**Comment by DylanLukes** [comment]
The only solution I've found (which is probably not ideal) that works is:

```scala
lazy val diodeJS =
  ProjectRef(uri("git://github.com/suzaku-io/diode.git#scalajs-react-1.0.0"), "diodeJS")

lazy val diodeReact =
  ProjectRef(uri("git://github.com/suzaku-io/diode.git#scalajs-react-1.0.0"), "diodeReact")
```

Main issues are: 

1) You can't use cross build versions, so this is blocking 2.11=>2.12.
2) You can't use coursier, so reloading large projects can take forever.

**Comment by ochrons** [comment]
Support added in release 1.1.2
