### ISSUE TITLE
examples/treeview not working

### ISSUE THREAD

**Issue by vovateleport** [suzaku-io/diode#61]
Hi,
https://diode.suzaku.io/examples/treeview/ is not working with error

diode.suzaku.io/:24 Uncaught TypeError: SimpleApp is not a function
    at diode.suzaku.io/:24

**Comment by abdheshkumar** [comment]
@vovateleport you have to change code from ```SimpleApp().main();``` to ```SimpleApp.main();``` in index.html file.

**Comment by ochrons** [comment]
Fixed now
