### ISSUE TITLE
Update scala.js react to 1.1.0

### ISSUE THREAD

**Issue by ngbinh** [suzaku-io/diode#64]
https://github.com/japgolly/scalajs-react/blob/master/doc/changelog/1.1.0.md

**Comment by ochrons** [comment]
I take it Diode is not compatible with this new version right now?

**Comment by ngbinh** [comment]
I believe there are some small changes. Will send a PR soon

**Comment by malaman** [comment]
@ngbinh Which errors do you have with diode 1.1.2 and scalajs-react 1.1.0?

**Comment by cquiroz** [comment]
I have been using the combination of diode 1.1.2 and react 1.1.0 without any troubles besides the eviction warnings

**Comment by ochrons** [comment]
Done in Diode 1.1.3
