### ISSUE TITLE
startTime in Pending state is always reset when using PotAction.handler with progress updates

### ISSUE THREAD

**Issue by an-tex** [suzaku-io/diode#65]
Hi,
when using `PotAction.handler(progressInterval)` the original startTime is overwritten with every progress update:
```scala
case PotPending =>
    if (value.isPending && progressInterval > Duration.Zero)
        updated(value.pending()
```

the `value.pending()` goes to
```scala
final case class Pending(startTime: Long = Pot.currentTime) {
  override def pending(startTime: Long = Pot.currentTime) = copy(startTime)
}
```

Which always returns a Pot copy with the current time.

Shouldn't here the startTime be used from the existing instance? I thought to make a PR already but then I've seen that the tests explicitly test for this behaviour.

```scala
assert(pend.pending(startTime0).asInstanceOf[PendingBase].startTime == startTime0)
assert(pend.pending().asInstanceOf[PendingBase].startTime > startTime0)
```

Is my assumption wrong or how can I retrieve the overall duration of the Pending pot.

**Comment by ochrons** [comment]
This is a good question! I suppose there are use cases for both approaches, but I think what you propose is the more natural default. So feel free to make a PR to change the behavior of `pending` in `Pending` and `PendingStale` to keep the current `startTime` value. The current implementation is probably just a result of copy-pasting the implementation from `Ready`/`Empty` :)
