### ISSUE TITLE
How to reset root model

### ISSUE THREAD

**Issue by kroeberk** [suzaku-io/diode#67]
Dear diode-team,

first of all: This is a really great library. I just have one issue with implementing a model reset functionality. I need a way to reset the ENTIRE root model to the initial state. Sadly, all the zoomTo functions don't allow me to access the root model, because they claim "an illegal field reference". How would I implement an action handler that resets the entire model?

~Karl

**Comment by kroeberk** [comment]
To clarify, this:

<img width="718" alt="bildschirmfoto 2017-09-29 um 11 27 07" src="https://user-images.githubusercontent.com/5459798/31009870-31ccc86a-a509-11e7-8b96-5351934fc452.png">

Leads to this:

<img width="1116" alt="bildschirmfoto 2017-09-29 um 11 27 13" src="https://user-images.githubusercontent.com/5459798/31009875-36abeaaa-a509-11e7-9076-f2a934db0149.png">

**Comment by ochrons** [comment]
The `ActionHandler` helper class might mislead you in this, but underneath the handler function is actually just

```scala
type HandlerFunction = (M, Any) => Option[ActionResult[M]]
```
An instance of `ActionHandler` is implicitly converted to this type, but you don't have to use `ActionHandler` and provide the function directly.

So you can use a function like
```scala
def resetModel(model: M, action: Any): Option[ActionResult[M]] = action match {
  case Reset() => Some(ModelUpdate(StatePersister.EMPTY_ROOT_STATE))
  case _ => None
}
```
and pass it to the `composeHandlers` with your other handlers.

**Comment by kroeberk** [comment]
Thank you very much, that's was fast. Works perfectly!
