### ISSUE TITLE
scalajs-react 1.2 support

### ISSUE THREAD

**Issue by erdeszt** [suzaku-io/diode#77]
I saw that the changes to support scalajs-react 1.2 got merged to master and wondering if it's possible to release a new version with the upgraded dep.

**Comment by mikla** [comment]
+1

**Comment by rpiaggio** [comment]
+1

**Comment by glmars** [comment]
I suppose we also should upgrade examples (please, see `example` folder) and improve implementation of `ReactPot` (it's now possible to use `EmptyVdom` instead of `VdomArray.empty()` if I understand correctly release notes of scalajs-react 1.2.0)

**Comment by ant8e** [comment]
Looks like this commit : https://github.com/suzaku-io/diode/commit/f9536500a1942e8b26aad0e7858320ea3d6618a4 fixes this issue.

**Comment by ochrons** [comment]
Released under version 1.1.3.120
